// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  biography: dynamic(() => import("./Biography")),
  contentindex: dynamic(() => import("./Contentindex")),
  hero: dynamic(() => import("./Hero")),
  techlist: dynamic(() => import("./Techlist")),
  text_block: dynamic(() => import("./TextBlock")),
};
